{
    guildID,
    staffPingID,
    members:[
        {
            memberID,
            warns,
            roles,
            permissions,
            badge,
        }
    ]
    serverLeaderboard:{
        {
            userID,
            points,
        }
    },
},
{
    guildID,
    staffPingID,
    members:[
        {
            memberID,
            warns,
            roles,
            permissions,
            badge,
        }
    ]
    serverLeaderboard:{
        {
            userID,
            points,
        }
    },
}